name: "release extension"
description: "Generate a release for a precompiled gh extension"
inputs:
  # TODO should repository be an input? when would github.repository not be useful?
  platforms:
    description: 'comma separated list of platform identifiers, like: "darwin-amd64,windows-arm64"'
    default: TODO
  sign:
    description: 'whether or not to sign release assets'
    default: false
  build_script:
    description: "path to your repository's build script. it must create a dist/ directory at the top level with any release assets. by default, assumes Go code."
    default: ""
runs:
  using: composite
  steps:
    # TODO use build_script
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
    - run: ${{ github.action_path }}/script/build_wrapper.sh
      with:
        platforms: ${{ inputs.platforms }}
        sign: ${{ inputs.sign }}
      shell: bash
    # TODO signing
    - run: ${{ github.action_path}}/script/release.sh
      shell: bash
