name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cli/gh-extension-precompile@v1.0.3
        with:
          platforms: "darwin-amd64,darwin-arm64,linux-386linux-amd64,linux-arm64,windows-386,windows-amd64"
